In [1]:
import numpy as np
import pylab as pl
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
%matplotlib inline
from sklearn.model_selection import StratifiedShuffleSplit
iris = datasets.load_iris()
digits = datasets.load_digits()
import gzip
import csv
import pandas
from pandas.plotting import scatter_matrix

    

In [2]:
datdir = '/home/rhlozek/pubData/'
filename = 'plasticc_training_set.csv.gz'
nrows=20
names = ['object_id', 'mjd', 'passband', 'flux', 'flux_err', 'detected_bool']

df = pandas.read_csv(datdir+filename, compression='gzip')  #, names=names)
meta = pandas.read_csv(datdir+'plasticc_training_set_metadata.csv', na_values='NaN', na_filter=True)
meta = meta.fillna(value=-999)
    
clf = svm.SVC(gamma=0.001, C=100.)

In [3]:
print(df.head())
print(meta.head())

   object_id         mjd  passband        flux   flux_err  detected_bool
0        615  59750.4229         2 -544.810303   3.622952              1
1        615  59750.4306         1 -816.434326   5.553370              1
2        615  59750.4383         3 -471.385529   3.801213              1
3        615  59750.4450         4 -388.984985  11.395031              1
4        615  59752.4070         2 -681.858887   4.041204              1
   object_id          ra       decl        gall       galb  ddf_bool  \
0        615  349.046051 -61.943836  320.796530 -51.753706         1   
1        713   53.085938 -27.784405  223.525509 -54.460748         1   
2        730   33.574219  -6.579593  170.455585 -61.548219         1   
3        745    0.189873 -45.586655  328.254458 -68.969298         1   
4       1124  352.711273 -63.823658  316.922299 -51.059403         1   

   hostgal_specz  hostgal_photoz  hostgal_photoz_err   distmod  mwebv  target  
0         0.0000          0.0000              0.0

In [99]:
feature_names = ['mjd', 'passband', 'flux', 'flux_err', 'detected_bool']
X = df.groupby('object_id')

#.get_group(('mjd', 'passband'))

#bo = g.get_group(('foo','two'))
y = meta['target']
#X.size().to_frame(name = 'count').reset_index()
print(list(X).iloc[0:2])


#X.describe().head()
#print(len(X))
#print(X.head())
#for k, gp in X:
#    print('key=' + str(k))
    #print(gp)
#print(dict(list(X)))
#df.groupby('object_id').flux.hist(alpha=0.4)
#scatter_matrix(X, alpha=0.2, figsize=(6, 6), diagonal='kde')


AttributeError: 'list' object has no attribute 'iloc'

In [98]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
print(len(X))
#print(X.count())
sss = StratifiedShuffleSplit(n_splits=2,test_size=0.5, train_size=0.5, random_state=0)

#df[df.groupby(['id'])['year']
for train_index, test_index in sss.split(X, y):
    
    #print("TRAIN:", len(train_index), "TEST:", len(test_index))
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]


7848


AttributeError: Cannot access callable attribute 'iloc' of 'DataFrameGroupBy' objects, try using the 'apply' method

In [23]:
from sklearn.model_selection import TimeSeriesSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])
print(X)
print(y)
tscv = TimeSeriesSplit(n_splits=2)
print(tscv)  

for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]




[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[1 2 3 4]
TimeSeriesSplit(max_train_size=None, n_splits=2)
TRAIN: [0 1] TEST: [2]
TRAIN: [0 1 2] TEST: [3]


In [9]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
print(X)
sss = StratifiedShuffleSplit(n_splits=3, test_size=0.5, random_state=0)
sss.get_n_splits(X, y)
3
print(sss)       
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]


[[1 2]
 [3 4]
 [1 2]
 [3 4]]
StratifiedShuffleSplit(n_splits=3, random_state=0, test_size=0.5,
            train_size=None)
TRAIN: [1 2] TEST: [3 0]
TRAIN: [0 2] TEST: [1 3]
TRAIN: [0 2] TEST: [3 1]
